# -*- coding: utf-8 -*-
"""Sephora_Group_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fth9nedg0PBECjH1d1-FawXwgvt4v7cs

# Sephora

### Marijo, Caro, Valentina, Sebastián

#### (Part 01) Import data
"""

#Upload dataframe

from google.colab import files
uploaded = files.upload()

# read the data

import pandas as pd
df = pd.read_csv('product_info Sephora.csv')
df

# DF DIMENSSIONS
df.shape

# DF INFORMATIONS
df.info()

"""#### (Part 02) Clean data"""

df.isna().sum()
df

# CHECK MISSING VALUES BY COLUMN
df.isna().sum()

# CLEAN DF BY DROP MISSING VALUES
# SELECT THE num_cols
num_cols = df.select_dtypes(include="number").columns

#REPLACE THE MISSING VALUES BY THE MEAN
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())
df

# CLEAN DF BY DROP MISSING QUALITATIVE VALUES
# SELECT THE cat_cols
cat_cols = df.select_dtypes(include="object").columns

#REPLACE THE MISSING VALUES BY THE MODE
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode())
df

"""#### (Part 03) Data frame manipulation

"""

# Find the maximum "reviews" "product_name" name
max_oa = df["reviews"].max()
max_oa

max_oa_name = df[df["reviews"] == max_oa]["product_name"]
max_oa_name

# Find the minimum "reviews" "product_name" name
min_oa = df["reviews"].min()
min_oa

min_oa_name = df[df["reviews"] == min_oa]["product_name"]
min_oa_name

# Find the maximum "rating" "product_name" name
max_oa = df["rating"].max()
max_oa

max_rait_name= df[df['rating'] == df['rating'].max()][['product_name', "rating"]]
max_rait_name

# Find the minimum "rating" "product_name" name
min_oa = df["rating"].min()
min_oa

min_rait_name= df[df['rating'] == df['rating'].min()][['product_name', "rating"]]
min_rait_name

# Print the Total of "rating" & Total of "reviews" by "product_name"
tab1 = df.groupby("product_name")[["rating", "reviews"]].sum().reset_index()
tab1

"""#### (Part 05) Data Visualisation"""

#The graph of average of "Rating" by “Product category”.
import matplotlib.pyplot as plt
tab1=df.groupby("primary_category")["rating"].mean().reset_index()
tab1.plot(x="primary_category", y="rating", kind="bar", color="black")
tab1

#Graph the total "price" by "product category"
tab2=df.groupby("primary_category")["price_usd"].sum().reset_index()
tab2.plot(x="primary_category", y="price_usd", kind="bar", color="black")
tab2

#The graph of the mean of ('rating' and 'loves_count’) by 'primary_category‘
import matplotlib.pyplot as plt
import seaborn as sns

graph1= df.groupby("primary_category")[["rating", "loves_count"]].mean().reset_index()
graph1.plot(x="primary_category",
            y=["rating", "loves_count"],
            kind="bar", color=["blue", "orange"])
plt.title("Mean of Ratings and Loves Count by Category")
plt.xlabel("Category")
plt.ylabel("Mean")
plt.legend(["Ratings", "Loves Count"])
plt.show()

#Read 'reviews' & 'loves count' data and show it using a scatter plot
plt.scatter(df["reviews"],
            df["loves_count"],
            color="blue")
plt.show()

#In Pie chart display the maximum of 'price_usd' per 'primary_category'

graph4= df.groupby("primary_category")[["price_usd"]].max().reset_index()
graph4.plot(x="primary_category",
            y= "price_usd",
            kind= "pie",
            autopct="%1.2f%%")

"""#### (Part 04) Data Analysis"""